### ISSUE TITLE
Feat: Add formatting for entire buffer

### ISSUE THREAD

**Issue by Wansmer** [LostNeophyte/null-ls-embedded#4] opened 2022-12-03 09:06 UTC
At the moment, `require("null-ls-embedded").buf_format()` formatted only embedded blocks, but no format whole buffer. It required calling `vim.lsp.buf.format()'` after `require("null-ls-embedded").buf_format()`.  
My suggestion: to add option for ability formatting entire buffer with formatter for buffer by default (no only with null-ls). It allows use one keymap for formatting and no require use two different commands for one action.
It can be as an option in setup or behavior by default.

https://user-images.githubusercontent.com/46977173/205433294-79037a66-6100-4b64-aae3-ead0096fff95.mov

**Comment by LostInTheLogs** [comment] 2022-12-03 09:18
what about a feature that would allow to add this plugin to sources in null-ls.setup and it would run on vim.lsp.buf.format with the other ones

**Comment by Wansmer** [comment] 2022-12-03 09:22
> what about a feature that would allow to add this plugin to sources in null-ls.setup and it would run on vim.lsp.buf.format with the other ones

Yes, it would be cool too

**Comment by Wansmer** [comment] 2022-12-03 09:33
Just in case, I created a pull request for this feature, if you decide to implement it (#5)

**Comment by LostInTheLogs** [comment] 2022-12-03 09:36
just calling `vim.lsp.buf.format` might be a bit problematic, because it's argument such as timeout and filter would need to be configurable

**Comment by Wansmer** [comment] 2022-12-03 09:37
Ok, will learn more it about

**Comment by LostInTheLogs** [comment] 2022-12-04 10:12
I think the refactor is complete, it features a null-ls source so it will run together with the other formatters, could you check if the [refactor branch](https://github.com/LostNeophyte/null-ls-embedded/tree/refactor) works for you?

**Comment by Wansmer** [comment] 2022-12-04 10:36
It works for vue (formatting entire file, formatter for '.vue' - eslint).
No work for html (formatting embedded langs (css, js), no formatting entire file. Formatter for '.html' - html-lsp).
`ignore_langs` seems like no working (tested with lang 'vim' in 'lua').
When call command `require("null-ls-embedded").buf_format()`, plugin throw error:
<img width="1073" alt="Снимок экрана 2022-12-04 в 13 28 02" src="https://user-images.githubusercontent.com/46977173/205485987-c2c7c911-481b-450d-b4d6-54bf0b49adba.png">

**Comment by Wansmer** [comment] 2022-12-04 10:44
Also, I tried run formatting in '.md' with 'html' block - no works:
```html
<div>
test
</div>
```

**Comment by LostInTheLogs** [comment] 2022-12-04 10:48
> Also, I tried run formatting in '.md' with 'html' block - no works:
> 
> ```
> <div>
> test
> </div>
> ```

if you put just 
```html
<div>
test
</div>
````
in a html file, it probably won't format it either, I guess I can add treesitter indentation as a fallback in the future

**Comment by LostInTheLogs** [comment] 2022-12-04 10:59
buf_format should be fixed now

**Comment by LostInTheLogs** [comment] 2022-12-04 11:06
`:lua vim.lsp.buf.format()` formats both with html-lsp and null-ls for me

**Comment by Wansmer** [comment] 2022-12-04 11:18
It not work for me. First I thought that it because two lsp attached for buffer (emmet and html), but when I disable emmet - nothing to change.

https://user-images.githubusercontent.com/46977173/205487432-439ab1e8-eb6d-4c29-8c1b-23abcc33f343.mov

**Comment by LostInTheLogs** [comment] 2022-12-04 11:23
send a screenshot of `:LspInfo`

**Comment by Wansmer** [comment] 2022-12-04 11:29
LspInfo:
<img width="1605" alt="Снимок экрана 2022-12-04 в 14 27 24" src="https://user-images.githubusercontent.com/46977173/205487862-fd6b2457-c594-466b-be73-28d64b8232a6.png">

NullLsInfo:
<img width="1540" alt="Снимок экрана 2022-12-04 в 14 27 53" src="https://user-images.githubusercontent.com/46977173/205487853-d56ff683-dae2-475c-b729-a1cd60415672.png">

**Comment by LostInTheLogs** [comment] 2022-12-04 11:33
does `:lua vim.lsp.buf.format({id = 1})` format the html?

**Comment by Wansmer** [comment] 2022-12-04 11:40
In that case throws error:
<img width="528" alt="Снимок экрана 2022-12-04 в 14 39 34" src="https://user-images.githubusercontent.com/46977173/205488334-a3021940-94d0-42d2-8e8d-56cc208014e4.png">

**Comment by LostInTheLogs** [comment] 2022-12-04 11:40
does html formatting  work if you don't add `null-ls-embedded` to the null-ls sources?

**Comment by Wansmer** [comment] 2022-12-04 11:52
> does html formatting work if you don't add `null-ls-embedded` to the null-ls sources?

Yes. And also entire html formatting with PR #5

**Comment by LostInTheLogs** [comment] 2022-12-04 11:53
that's weird, what's your neovim version?

**Comment by LostInTheLogs** [comment] 2022-12-04 11:55
and does the pr work with the `refactor` branch?

**Comment by Wansmer** [comment] 2022-12-04 11:58
> that's weird, what's your neovim version?

0.8.1

> and does the pr work with the `refactor` branch?

No, I no added PR to refactor. I mean, that approach from this PR is work. Maybe it helps you fixed this.

**Comment by LostInTheLogs** [comment] 2022-12-04 12:13
what about `:lua vim.lsp.buf.format({name = "html"})`

**Comment by Wansmer** [comment] 2022-12-04 12:16
> what about `:lua vim.lsp.buf.format({name = "html"})`

Throws same error.

**Comment by LostInTheLogs** [comment] 2022-12-04 12:16
Is your neovim config public so I could try it?

**Comment by Wansmer** [comment] 2022-12-04 12:19
> Is your neovim config public so I could try it?

Yes, sure: https://github.com/Wansmer/nvim-config

**Comment by LostInTheLogs** [comment] 2022-12-04 12:22
with my config it works in 0.8.1

**Comment by LostInTheLogs** [comment] 2022-12-04 12:46
and it doesn't work with your config

**Comment by Wansmer** [comment] 2022-12-04 12:51
> and it doesn't work with your config

It is strange. I hope no anyone not will have similar problem.

**Comment by LostInTheLogs** [comment] 2022-12-04 12:52
I think this https://github.com/Wansmer/nvim-config/blob/389e52986cc0b4b9795b926602b30679bdbe7876/lua/config/lsp/default.lua#L26-L32 is the problem, you don't set formatting as a capability there

**Comment by LostInTheLogs** [comment] 2022-12-04 12:53
changing https://github.com/Wansmer/nvim-config/blob/389e52986cc0b4b9795b926602b30679bdbe7876/lua/config/lsp/init.lua#L30 to `lsp[server_name].setup({})` makes it work

**Comment by Wansmer** [comment] 2022-12-04 12:56
I think the problem not in capabilities, but in formatters:  https://github.com/Wansmer/nvim-config/blob/main/lua/config/lsp/formatters.lua

Later I'll testing it.

**Comment by LostInTheLogs** [comment] 2022-12-04 12:58
you're right, I commented [formatters.lua](https://github.com/Wansmer/nvim-config/blob/main/lua/config/lsp/formatters.lua) out and it does work

**Comment by LostInTheLogs** [comment] 2022-12-04 13:01
that's the problem: https://github.com/Wansmer/nvim-config/blob/389e52986cc0b4b9795b926602b30679bdbe7876/lua/config/lsp/formatters.lua#L57-L53
 
you're setting `documentFormattingProvider` to false for all servers that aren't null-ls if there is a null-ls formatter available for the filetype

**Comment by Wansmer** [comment] 2022-12-04 13:13
Yes, you're right. I disabled this and it worked. 
Btw, this part of config I found at popular [blog](https://alpha2phi.medium.com). Perhaps a lot of people use the same code in their config. I think, you need to note about this in readme in the future.

Also, `ignore_langs` still not applied with 'vim'.

**Comment by LostInTheLogs** [comment] 2022-12-04 13:18
> Also, ignore_langs still not applied with 'vim'.

I'll check that, how are you setting it, and what are you using to format?

**Comment by Wansmer** [comment] 2022-12-04 13:21
E.G.:
```lua
vim.cmd([[
  augroup packer_user_config
    autocmd!
    autocmd BufWritePost plugins.lua source <afile> | PackerSync
  augroup end
]])
```
formats to
```lua
vim.cmd([[  augroup packer_user_config
    autocmd!
    autocmd BufWritePost plugins.lua source <afile> | PackerSync
  augroup end
]])
```

Code from `plugins.lua` from my config.

**Comment by LostInTheLogs** [comment] 2022-12-04 13:22
yep, reproduced, will fix that

**Comment by LostInTheLogs** [comment] 2022-12-04 13:33
It should be fixed now

**Comment by Wansmer** [comment] 2022-12-04 13:40
> It should be fixed now

Hm, no, same result after plugin updated.

**Comment by LostInTheLogs** [comment] 2022-12-04 13:44
and now?

**Comment by Wansmer** [comment] 2022-12-04 13:48
Great! Now works

**Comment by LostInTheLogs** [comment] 2022-12-04 13:53
Thanks for your time and cooperation :)

**Closed as completed by LostInTheLogs** 2022-12-04 13:53 UTC
